# Generated by Django 2.0.1 on 2019-10-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191012_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_owner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='project',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
