# Generated by Django 2.0.1 on 2019-10-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191012_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_annoteated',
            field=models.BooleanField(default=False, verbose_name='文本是否已被标注'),
        ),
    ]
