# Generated by Django 2.0.1 on 2019-10-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191014_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='文本是否被逻辑删除'),
        ),
    ]
