# Generated by Django 2.0.1 on 2019-10-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_document_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='document',
            new_name='document_id',
        ),
    ]
