# Generated by Django 2.0.1 on 2019-10-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191015_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='document_id',
            new_name='doc_id',
        ),
    ]
