# Generated by Django 2.0.1 on 2019-10-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191015_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='doc_id',
            new_name='document',
        ),
    ]
