# Generated by Django 2.0.1 on 2019-10-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191015_1321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('start_offset', 'end_offset')},
        ),
    ]
