# Generated by Django 2.0.1 on 2019-10-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191015_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='annotated_by',
        ),
    ]
