# Generated by Django 2.0.1 on 2019-10-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_document_annotated_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('start_offset', 'end_offset', 'document')},
        ),
    ]
