# Generated by Django 2.0.1 on 2019-10-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191015_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id'], 'verbose_name': '文书表'},
        ),
    ]
