# Generated by Django 2.0.1 on 2019-10-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191016_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '文书表'},
        ),
    ]
