# Generated by Django 2.0.1 on 2019-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191016_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='文档标题'),
        ),
    ]
