# Generated by Django 2.0.1 on 2019-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191018_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('algorithm_type', models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence')], help_text='算法类型', max_length=30)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mini_quantity', models.IntegerField(verbose_name='最小训练集')),
                ('code_url', models.CharField(max_length=255, unique=True, verbose_name='算法代码路径')),
                ('model_url', models.CharField(max_length=255, unique=True, verbose_name='算法模型路径')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='user',
            new_name='annoted_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
