# Generated by Django 2.0.1 on 2019-10-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191029_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_user',
            name='role',
            field=models.CharField(choices=[('project_owner', 'project_owner'), ('user', 'user')], max_length=20),
        ),
    ]
