# Generated by Django 2.0.1 on 2019-10-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_user',
            options={'verbose_name': '项目用户表'},
        ),
        migrations.AlterUniqueTogether(
            name='project_user',
            unique_together={('project', 'user')},
        ),
        migrations.AlterModelTable(
            name='project_user',
            table='project_user',
        ),
    ]
