# Generated by Django 2.0.1 on 2019-10-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191029_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_User',
            new_name='ProjectUser',
        ),
        migrations.AlterModelTable(
            name='projectuser',
            table='project_user_relationship',
        ),
    ]
