# Generated by Django 2.0.1 on 2019-10-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20191030_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
