# Generated by Django 2.0.1 on 2019-10-30 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(help_text='用户', through='api.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
