# Generated by Django 2.0.1 on 2019-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20191030_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_role',
            field=models.CharField(blank=True, choices=[('ordinary_user', 'ordinary_user'), ('system_manager', 'system_manager'), ('super_user', 'super_user')], help_text='项目类型', max_length=30, null=True),
        ),
    ]
