# Generated by Django 2.0.1 on 2019-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_user_system_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='description',
            field=models.TextField(default='', verbose_name='算法描述'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='end_offset',
            field=models.IntegerField(verbose_name='标记结束下标'),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(blank=True, choices=[('ordinary_user', 'ordinary_user'), ('system_manager', 'system_manager'), ('super_user', 'super_user')], help_text='系统角色', max_length=30, null=True),
        ),
    ]
