# Generated by Django 2.0.1 on 2019-11-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20191101_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='system_role',
        ),
    ]
