# Generated by Django 2.0.1 on 2019-11-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_user_system_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.Label', verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('project_owner', 'project_owner'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
