# Generated by Django 2.0.1 on 2019-11-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20191104_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(blank=True, choices=[('project_owner', 'project_owner'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
