# Generated by Django 2.0.1 on 2019-11-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20191104_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='code_url',
            field=models.CharField(max_length=255, null=True, verbose_name='算法代码路径'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='model_url',
            field=models.CharField(max_length=255, null=True, verbose_name='算法模型路径'),
        ),
    ]
