# Generated by Django 2.0.1 on 2019-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20191122_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
