# Generated by Django 2.0.1 on 2019-11-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20191115_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='text_color',
        ),
    ]
