# Generated by Django 2.0.1 on 2019-11-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20191122_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='algorithm',
        ),
    ]
