# Generated by Django 2.0.1 on 2019-11-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_label_text_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'text'), ('project', 'prefix_key', 'suffix_key')},
        ),
    ]
