# Generated by Django 2.0.1 on 2019-12-16 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_delete_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_complete', models.BooleanField(default=False, help_text='用户')),
                ('document', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('project', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('user', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='documents',
            field=models.ManyToManyField(help_text='用户', through='api.Task', to='api.Document'),
        ),
    ]
