# Generated by Django 2.0.1 on 2019-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20191217_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='是否被分配'),
        ),
    ]
