# Generated by Django 2.0.1 on 2019-11-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('algorithm_type', models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence')], help_text='算法类型', max_length=30)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mini_quantity', models.IntegerField(verbose_name='最小训练集')),
                ('code_url', models.FileField(upload_to='algorithm/')),
                ('model_url', models.CharField(max_length=255, null=True, verbose_name='算法模型路径')),
                ('description', models.TextField(default='', verbose_name='算法描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='算法是否删除删除')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
