# Generated by Django 2.0.1 on 2019-11-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='code_url',
            new_name='algorithm_file',
        ),
    ]
