# Generated by Django 2.0.1 on 2019-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20191127_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='algorithm_file',
            field=models.FileField(upload_to='C:\\Users\\wangzhaochuan930206\\Desktop\\algorithm'),
        ),
    ]
