# Generated by Django 2.0.1 on 2019-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_auto_20191202_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='algorithm_file',
            field=models.FileField(upload_to='D:\\algorithm'),
        ),
    ]
