# Generated by Django 2.0.1 on 2019-12-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_auto_20191202_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='algorithm_file',
            field=models.FileField(upload_to=''),
        ),
    ]
