# Generated by Django 2.0.1 on 2019-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_auto_20191202_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='algorithm_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
