# Generated by Django 2.0.1 on 2019-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_algorithm_algorithm_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='algorithm_file',
            field=models.FileField(upload_to='algorithm/'),
        ),
    ]
