# Generated by Django 2.0.1 on 2019-12-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0008_auto_20191202_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='algorithm_path',
        ),
    ]
